### ISSUE TITLE
What is DOIfolder?

### ISSUE THREAD

**Issue by yj373** [mikejhuang/LungNoduleDetectionClassification#4]
Hi! When I try to run your ProcessNoduleDataset, I don't know what should be set as the value of DOIfolderpath. Is it the path towards the LIDC imaging data?

**Comment by mikejhuang** [comment]
Yes, it is.

**Comment by yj373** [comment]
Tank you for replying me! It seems like you are trying to access the image data using 'Series UID'. But after I download the LIDC dataset, there are not any folders named by 'Series UID'. Thus, the list of 'patents' is empty. Have you ever met this problem?

**Comment by mikejhuang** [comment]
The 'Series UID' is in LIDC-IDRI_MetaData.csv

Each patient in the LIDC dataset should have several Series UID folders.
Here's an example of one
path. LIDC\DOI\LIDC-IDRI-0001\1.3.6.1.4.1.14519.5.2.1.6279.6001.175012972118199124641098335511
