### ISSUE TITLE
Could you show me your paper?

### ISSUE THREAD

**Issue by sunhaotian130911** [mikejhuang/LungNoduleDetectionClassification#5]
i want to learn more about your project，thx

**Comment by mikejhuang** [comment]
There's a paper in the repository.
https://github.com/mikejhuang/LungNoduleDetectionClassification/blob/master/Automated%20Extraction%20and%20Classification%20of%20Pulmonary%20Lung%20Nodules%20from%20CT%20Scans.pdf
